# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14RhmOz7mrNamFfM8b_niamX-KtWoDTXO
"""

count=0
while count<3:
R=input("Enter the username: ")
Q=input("Enter the password :")

if R=="Micheal" and Q=="e3$WT89x":
print("successfully logged in"
else:
count+=1
print("Invalid username and password")
if count=3:
print("Account Locked")
