# -*- coding: utf-8 -*-
"""SUSHANT_4AL18EC400.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BrUoZIWSlauegVm1ToYEIipW7hWpQtym
"""

trial=0
while trial<3:
    username=input('Enter your username : ')
    password=input('Enter your password : ')
    if username=='Micheal' and password=='e3$WT89x':
        print('You have successfully login')
        break
    else:
        print('Invalid username or password')
        trial+=1
    if trial==3:
        print('Account locked')